# Generated by Django 4.1.7 on 2023-04-08 14:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_book_readers_alter_book_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbookrelation',
            unique_together={('user', 'book')},
        ),
    ]
